### ISSUE TITLE
PR guidelines + lint format

### ISSUE THREAD

**Issue by thiagomorales** [nmggithub/fbsdk-ts#1]
Hello, first thanks for your working in this project.

I'have implemented initial support for conversions-api (pixel server events) and want to open PR asap.
Could you share/update your definitions about project lint/format -- to avoid huge formatting changes?

Thanks.
Regards.

**Comment by nmggithub** [comment]
Hey! Thank you for your support of this project!

I have just made a commit with a `.prettierrc` file. Please use it to format your additions. To build, please run `npm run all` and test the built version of the module before submitting your PR.

Thanks again, and I hope to see your PR soon.

**Comment by thiagomorales** [comment]
Thank you. I'll open this PR asap.
Regards.
